### ISSUE TITLE
Themes for code blocks and tabs.

### ISSUE THREAD

**Issue by rafegoldberg** [readmeio/api-explorer#619]
We'd like to be able to set global theme colors for our markdown code blocks, so users can add custom highlight colors. That might look something like this:

```css
.markdown-body {
  --md-code-background: #13032b;
  --md-code-text: white;
  --md-code-tabs: #5f3c94;
  --md-code-radius: #5f3c94;
}
```

Which would give you something like this:

![image](https://user-images.githubusercontent.com/886627/80263775-a0b0de80-8646-11ea-8d58-b2cb21a68707.png)
